services:
  easy-continuity-api-uat:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - ENVIRONMENT=UAT
    ports:
      - "5004:80"
    depends_on:
      - postgres-uat
    environment:
      ASPNETCORE_ENVIRONMENT: UAT
      ConnectionStrings__ECPostgresConnection: "Host=postgres-uat;Database=ecdb_uat;Username=${DB_USER};Password=${DB_PASSWORD}"
      CLOUDINARY_CLOUD_NAME: ${CLOUDINARY_CLOUD_NAME}
      CLOUDINARY_API_KEY: ${CLOUDINARY_API_KEY}
      CLOUDINARY_API_SECRET: ${CLOUDINARY_API_SECRET}
      # JWT Settings
      JWT_KEY: ${JWT_KEY}
      JWT_ISSUER: ${JWT_ISSUER}
      JWT_AUDIENCE: ${JWT_AUDIENCE}
      JWT_EXPIRY_MINUTES: ${JWT_EXPIRY_MINUTES}
    env_file:
      - .env

  postgres-uat:
    image: postgres
    environment:
      POSTGRES_DB: ecdb_uat
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5436:5432"
    volumes:
      - db-uat-data:/var/lib/postgresql/data
    env_file:
      - .env

  pgadmin-uat:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "5054:80"
    depends_on:
      - postgres-uat
    volumes:
      - pgadmin-uat-data:/var/lib/pgadmin
    env_file:
      - .env

volumes:
  db-uat-data:
  pgadmin-uat-data: