services:
  easy-continuity-api-local:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "5001:80"
    depends_on:
      - postgres-local
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__ECPostgresConnection: "Host=postgres-local;Database=ecdb_local;Username=${DB_USER};Password=${DB_PASSWORD}"
      CLOUDINARY_CLOUD_NAME: ${CLOUDINARY_CLOUD_NAME}
      CLOUDINARY_API_KEY: ${CLOUDINARY_API_KEY}
      CLOUDINARY_API_SECRET: ${CLOUDINARY_API_SECRET}
    env_file:
      - .env

  postgres-local:
    image: postgres
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5433:5432"
    volumes:
      - db-local-data:/var/lib/postgresql/data
    env_file:
      - .env

  pgadmin-local:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "8081:80"
    depends_on:
      - postgres-local
    volumes:
      - pgadmin-local-data:/var/lib/pgadmin
    env_file:
      - .env

volumes:
  db-local-data:
  pgadmin-local-data: