version: '3.9'

services:
  easy-continuity-api-preprod:
    build:
      context: .
      dockerfile: Dockerfile.preprod
    ports:
      - "5000:80"
    depends_on:
      - postgres

  postgres:
    image: postgres
    environment:
      POSTGRES_DB: ecdb
      POSTGRES_USER: johnz
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres_password
    ports:
      - "5432:5432"
    volumes:
      - db-preprod-data:/var/lib/postgresql/data
    secrets:
      - postgres_password

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: jz@ec.com
      PGADMIN_DEFAULT_PASSWORD_FILE: /run/secrets/pgadmin_password
    ports:
      - "8080:80"
    depends_on:
      - postgres
    secrets:
      - pgadmin_password

volumes:
  db-preprod-data:

secrets:
  postgres_password:
    file: ./postgres_password.txt
  pgadmin_password:
    file: ./pgadmin_password.txt
