services:
  easy-continuity-api-test:
    build:
      context: .
      dockerfile: Dockerfile.test
    ports:
      - "5004:80"
    depends_on:
      - postgres-test
    environment:
      ASPNETCORE_ENVIRONMENT: UAT
      ConnectionStrings__ECPostgresConnection: "Host=postgres-test;Database=ecdb_test;Username=${DB_USER};Password=${DB_PASSWORD}"
      CLOUDINARY_CLOUD_NAME: ${CLOUDINARY_CLOUD_NAME}
      CLOUDINARY_API_KEY: ${CLOUDINARY_API_KEY}
      CLOUDINARY_API_SECRET: ${CLOUDINARY_API_SECRET}
    env_file:
      - .env

  postgres-test:
    image: postgres
    environment:
      POSTGRES_DB: ecdb_test
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5436:5432"
    volumes:
      - db-test-data:/var/lib/postgresql/data
    env_file:
      - .env

  pgadmin-test:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "5054:80"
    depends_on:
      - postgres-test
    volumes:
      - pgadmin-test-data:/var/lib/pgadmin
    env_file:
      - .env

volumes:
  db-test-data:
  pgadmin-test-data: