version: '3.9'

services:
  easy-continuity-api-preprod:
    build:
      context: .
      dockerfile: Dockerfile.preprod
    ports:
      - "5002:80"
    depends_on:
      - postgres-preprod
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__ECPostgresConnection=Host=${DB_HOST};Database=${DB_NAME};Username=${DB_USER};Password=${DB_PASSWORD}
    env_file:
      - .env.preprod

  postgres-preprod:
    image: postgres
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5434:5432"
    volumes:
      - db-preprod-data:/var/lib/postgresql/data
    env_file:
      - .env.preprod

  pgadmin-preprod:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "8082:80"
    depends_on:
      - postgres-preprod
    env_file:
      - .env.preprod

volumes:
  db-preprod-data: