services:
  easy-continuity-api-staging:
    build:
      context: .
      dockerfile: Dockerfile.staging
    ports:
      - "5003:80"
    depends_on:
      - postgres-staging
    environment:
      ASPNETCORE_ENVIRONMENT: Staging
      ConnectionStrings__ECPostgresConnection: "Host=postgres-staging;Database=ecdb_staging;Username=${DB_USER};Password=${DB_PASSWORD}"
      CLOUDINARY_CLOUD_NAME: ${CLOUDINARY_CLOUD_NAME}
      CLOUDINARY_API_KEY: ${CLOUDINARY_API_KEY}
      CLOUDINARY_API_SECRET: ${CLOUDINARY_API_SECRET}
    env_file:
      - .env

  postgres-staging:
    image: postgres
    environment:
      POSTGRES_DB: ecdb_staging
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5435:5432"
    volumes:
      - db-staging-data:/var/lib/postgresql/data
    env_file:
      - .env

  pgadmin-staging:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "5053:80"
    depends_on:
      - postgres-staging
    volumes:
      - pgadmin-staging-data:/var/lib/pgadmin
    env_file:
      - .env

volumes:
  db-staging-data:
  pgadmin-staging-data: