FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /app

COPY *.csproj ./
RUN dotnet restore

COPY . ./

RUN dotnet publish -c Debug -o out

FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS runtime
WORKDIR /app
COPY --from=build /app/out .

EXPOSE 80

# Checks if the root URL of the application responds.
HEALTHCHECK --interval=10s --timeout=3s --start-period=20s \
  CMD curl -f http://localhost/ || exit 1

ENTRYPOINT [ "dotnet", "EasyContinuity.dll" ]