version: '3.9'

services:
  easy-continuity-api-preprod:
    build:
      context: .
      dockerfile: Dockerfile.preprod
    ports:
      - "5002:80"
    depends_on:
      - postgres-preprod
    environment:
      - ConnectionStrings__ECPostgresConnection=Host=postgres-preprod;Database=ecdb_preprod;Username=johnz;Password=${POSTGRES_PASSWORD}

  postgres-preprod:
    image: postgres
    environment:
      POSTGRES_DB: ecdb_preprod
      POSTGRES_USER: johnz
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres_password
    ports:
      - "5434:5432"
    volumes:
      - db-preprod-data:/var/lib/postgresql/data
    secrets:
      - postgres_password

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: jz@ec.com
      PGADMIN_DEFAULT_PASSWORD_FILE: /run/secrets/pgadmin_password
    ports:
      - "8082:80"
    depends_on:
      - postgres_preprod
    secrets:
      - pgadmin_password

volumes:
  db-preprod-data:

secrets:
  postgres_password:
    file: ./postgres_password.txt
  pgadmin_password:
    file: ./pgadmin_password.txt
