name: SSH Test
on: workflow_dispatch

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: SSH Test
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.LINODE_HOST }}
          username: ${{ secrets.LINODE_USER }}
          key: ${{ secrets.LINODE_SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          debug: true
          script: echo "Connected"