name: SSH Debug
on: workflow_dispatch

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check secrets
        run: |
          echo "Host exists: ${{ secrets.SSH_HOST != '' }}"
          echo "Username exists: ${{ secrets.SSH_USERNAME != '' }}"
          echo "Key exists: ${{ secrets.SSH_PRIVATE_KEY != '' }}"
          
      - name: SSH Test
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          debug: true
          script: echo "Connected"