name: Deploy to Staging

on:
  workflow_dispatch:
    inputs:
      confirm:
        description: 'Type "yes" to confirm deployment to staging'
        required: true

jobs:
  deploy_to_staging:
    if: github.event.inputs.confirm == 'yes'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0 # Fetches the entire history of the repository

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.403'

    - name: Merge uat to staging
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        git checkout uat
        git pull origin uat
        git checkout staging
        git pull origin staging
        git merge --no-ff uat -m "Merge uat into staging [skip ci]"
        git push origin staging

    - name: Deploy to Staging Environment
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.LINODE_HOST }}
        username: ${{ secrets.LINODE_USER }}
        key: ${{ secrets.LINODE_SSH_PRIVATE_KEY }}
        port: ${{ secrets.SSH_PORT }}
        script: |
          # Stop only API containers
          docker ps | grep "easycontinuity-api" | awk '{print $1}' | xargs docker stop || true
          
          # Deploy to Staging
          cd EasyContinuity-API_Staging
          git fetch --all
          git checkout staging
          git pull origin staging
          
          # Bring up staging environment with clean builds
          docker compose -f docker-compose.staging.yml up --build -d