name: Manual Merge to Staging

on:
  workflow_dispatch:
    inputs:
      confirm:
        description: 'Type "yes" to confirm merge to staging'
        required: true

jobs:
  merge_to_preprod:
    if: github.event.inputs.confirm == 'yes'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0 # Fetches the entire history of the repository

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.403'

    - name: Merge dev to preprod
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        git checkout preprod
        git pull origin preprod
        git checkout main
        git merge --no-ff preprod
        git push origin main

    - name: Deploy to Linode
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.LINODE_HOST }}
        username: ${{ secrets.LINODE_USER }}
        key: ${{ secrets.LINODE_SSH_PRIVATE_KEY }}
        port: ${{ secrets.SSH_PORT }}
        script: |
          # First ensure UAT containers are properly stopped
          cd EasyContinuity-API_UAT
          docker compose -f docker-compose.uat.yml down --remove-orphans
          
          # Clean up Docker networks to prevent conflicts
          docker network prune -f
          
          # Move to staging directory and update code
          cd ../EasyContinuity-API_Staging
          git checkout preprod
          git pull origin preprod
          git checkout main
          git merge preprod
          
          # Stop staging containers if they exist
          docker compose -f docker-compose.staging.yml down --remove-orphans
          
          # Bring up staging environment with clean builds
          docker compose -f docker-compose.staging.yml up --build -d