name: Merge PR to Dev and Deploy to Test

on:
  push:
    branches: [ dev ]

jobs:
  deploy_to_test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0 # Fetches the entire history of the repository

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.403'

    - name: Merge dev to test
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        git checkout dev
        git pull origin dev
        git checkout test
        git pull origin test
        git merge --no-ff dev -m "Merge dev into test [skip ci]"
        git push origin test

    - name: Deploy to Test Environment
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.LINODE_HOST }}
        username: ${{ secrets.LINODE_USER }}
        key: ${{ secrets.LINODE_SSH_PRIVATE_KEY }}
        port: ${{ secrets.SSH_PORT }}
        script: |
          # Stop only API containers
          docker ps | grep "easycontinuity-api" | awk '{print $1}' | xargs docker stop || true
          
          # Deploy to Test
          cd EasyContinuity-API_Test
          git fetch --all
          git checkout test
          git pull origin test
          
          # Bring up test environment with clean builds
          docker compose -f docker-compose.test.yml up --build -d