name: Merge PR to Dev and Deploy to UAT

on:
  push:
    branches: [ dev ]

jobs:
  deploy_to_uat:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0 # Fetches the entire history of the repository

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.403'

    - name: Merge dev to uat
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        git checkout dev
        git pull origin dev
        git checkout uat
        git pull origin uat
        git merge --no-ff dev -m "Merge dev into uat [skip ci]"
        git push origin uat

    - name: Deploy to UAT Environment
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.LINODE_HOST }}
        username: ${{ secrets.LINODE_USER }}
        key: ${{ secrets.LINODE_SSH_PRIVATE_KEY }}
        port: ${{ secrets.SSH_PORT }}
        script: |
          # Stop only API containers
          docker ps | grep "easycontinuity-api" | awk '{print $1}' | xargs docker stop || true
          
          # Deploy to UAT
          cd EasyContinuity-API_UAT
          git fetch --all
          git checkout uat
          git pull origin uat
          
          # Bring up UAT environment with clean builds
          docker compose -f docker-compose.uat.yml up --build -d