name: Merge PR and Deploy to UAT

on:
  push:
    branches: [ main ]

jobs:
  merge_and_deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0 # Fetches the entire history of the repository

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.403'

    - name: Merge main to dev
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        git checkout main
        git pull origin main
        git checkout dev
        git merge --no-ff main
        git push origin dev

    - name: Deploy to Linode
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.LINODE_HOST }}
        username: ${{ secrets.LINODE_USER }}
        key: ${{ secrets.LINODE_SSH_PRIVATE_KEY }}
        port: ${{ secrets.SSH_PORT }}
        script: |
          # Ensure all running containers are stopped properly
          cd EasyContinuity-API_Staging
          docker compose -f docker-compose.staging.yml down --remove-orphans
          
          # Clean up Docker networks to prevent conflicts
          docker network prune -f
          
          # Deploy to UAT
          cd ../EasyContinuity-API_UAT
          git checkout main
          git pull origin main
          git checkout dev
          git merge main
          
          # Stop UAT containers if they exist
          docker compose -f docker-compose.uat.yml down --remove-orphans
          
          # Bring up UAT environment with clean builds
          docker compose -f docker-compose.uat.yml up --build -d